volumes:
  postgres-data:

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: guest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
